### PR TITLE
[sc-29289] Import biz glossary to Metaphor data document store

### PR DESCRIPTION
**Pull request by usefulalgorithm**
### 🤔 Why?

We want to make importing business glossary entries into Metaphor a bit easier.

### 🤓 What?

Added `document biz-glossary` command that has the following sub commands:
- `schema`: explains how the CSV file should look like
截圖 2024-10-17 晚上9 40 46

- `gen-example`: generates an example file
截圖 2024-10-17 晚上9 41 11

- `import`: imports the rows in the biz glossary file to the specified location, each row is a single data document.
截圖 2024-10-17 晚上9 40 29

### 🧪 Tested?

Tested on dev instance.

Before:

截圖 2024-10-17 晚上9 38 56

Run the import command:

截圖 2024-10-17 晚上9 40 29

After:

截圖 2024-10-17 晚上9 40 09

截圖 2024-10-17 晚上9 40 16

### CODE REVIEW

**Comment by mars-lan** [comment]
Also add a config to set the author (if possible)?

**Comment by mars-lan** [comment]
> Also add a config to set the author (if possible)?

nvm, it's part of the file content.

**Comment by usefulalgorithm** [comment]
> Also add a config to set the author (if possible)?

Our api currently does not support this.

**Comment by mars-lan** [comment]
`gen-example` sounds a bit misleading. Maybe rename it to `gen-template` instead?

**Review by mars-lan — APPROVED** [review]

**Pull request merged**
