### PR TITLE
[sc-29177] `settings.webhooks` subcommand

### PR DESCRIPTION
**Pull request by usefulalgorithm**
### 🤔 Why?

We want to manage webhooks but we don't want to have to write graphql queries ourselves. Need the CLI to provide this command.

### 🤓 What?

`aesop webhooks`
- `register`: registers a webhook
- `unregister`: unregisters a webhook
- `get`: get webhooks
- `get-payload-schema`: get payload schema for a trigger type

### 🧪 Tested?

Listing all available subcommands:
截圖 2024-10-07 晚上10 36 41

截圖 2024-10-07 晚上10 36 52

### CODE REVIEW

**Comment by usefulalgorithm** [comment]
Blocked by https://github.com/MetaphorData/app/pull/9559, don't merge this PR until that one has been merged!

**Review by mars-lan — COMMENTED** [review]
Why not just make webhook a top-level command?

**Comment by usefulalgorithm** [comment]
> Why not just make webhook a top-level command?

I felt it makes more sense to have it sit under settings. It is something that need configuring manually after all.

Do you think it is better to have it as its own top level command?

**Review by mars-lan — APPROVED** [review]
Please also update PR description for posterity.

**Pull request merged**
