### PR TITLE
[sc-28993] Remove, assign, and unassign tags

### PR DESCRIPTION
**Pull request by usefulalgorithm**
### 🤔 Why?

We can add tags, of course we should be able to remove tags.

#### Get existing tags

截圖 2024-09-26 晚上9 15 00

#### Deleting nonexisting tag

截圖 2024-09-26 晚上9 15 21

#### Deleting a tag, delete it again, and see it's really deleted

截圖 2024-09-26 晚上9 16 14

### 🧪 Tested?

See above.

### CODE REVIEW

**Review by mars-lan — COMMENTED** [review]
Tests?

**Comment by usefulalgorithm** [comment]
> Tests?

I think we want to make sure this is what we want. If not, there's no point writing tests for it.

**Comment by mars-lan** [comment]
> > Tests?
> 
> I think we want to make sure this is what we want. If not, there's no point writing tests for it.

Got it. Is it possible to delete a single tag using command line args? Or must you always specify the full JSON?

**Comment by usefulalgorithm** [comment]
> Got it. Is it possible to delete a single tag using command line args? Or must you always specify the full JSON?

I want it to be consistent with how `add` behaves, it only accepts an input file name or piped stdin.

**Pull request merged**
